import type { Bundle, City } from "../types";
import { formatHumanDate } from "../lib/dates";

interface Props {
  city: City;
  period: string;
  date: string;
  bundle: Bundle;
}

export function ExportButton({ city, period, date, bundle }: Props) {
  const periodMeta = bundle.periods.find((p) => p.label === period);
  const periodData = city.periods[period];
  const t = city.threat;

  // Plain markdown brief — analyst-readable, suitable for paste into reports
  const buildMarkdown = (): string => {
    const lines: string[] = [];
    lines.push(`# Cyber-Terrain Brief: ${city.name}`);
    lines.push(`**Date:** ${formatHumanDate(date)}`);
    lines.push(`**Target AS:** AS${city.asn}`);
    lines.push(`**Generated:** ${new Date().toISOString()}`);
    lines.push("");
    lines.push("## BLUF");
    lines.push(`Cyber-Terrain Threat Score **${t.score}/100** (${t.level.toUpperCase()})`);
    lines.push("");
    lines.push("## Threat Components");
    lines.push(`- Blackout signal:    ${t.components.blackout.toFixed(1)} / 40`);
    lines.push(`- Routing instability: ${t.components.instability.toFixed(1)} / 25`);
    lines.push(`- Russian-routed paths: ${t.components.russian_route.toFixed(1)} / 25`);
    lines.push(`- SORM exposure:      ${t.components.sorm_exposure.toFixed(1)} / 10`);
    lines.push("");
    lines.push("## Evidence");
    lines.push(`- Peer-count drop: ${t.evidence.peer_count_drop} peers`);
    lines.push(`- Max BGP UPDATE volume: ${t.evidence.max_bgp_updates_in_day} per 1-hour window`);
    lines.push(`- Russian-routed paths observed: ${t.evidence.russian_paths_count}`);
    if (t.evidence.sorm_ases_observed.length > 0) {
      lines.push(`- SORM-capable ASes in path: ${t.evidence.sorm_ases_observed.map(a => `AS${a}`).join(", ")}`);
    }
    lines.push("");

    if (periodData) {
      lines.push(`## BGP Sample at ${periodMeta?.description}`);
      lines.push(`${periodData.update_count} BGP UPDATE messages observed in 1-hour window.`);
      lines.push("");
      if (periodData.sample_paths.length > 0) {
        lines.push("### Sample AS Paths");
        for (const p of periodData.sample_paths.slice(0, 5)) {
          lines.push(`    ${p}`);
        }
        lines.push("");
      }
    }

    lines.push("## Narrative");
    const brief = bundle.briefs?.[city.name]?.[period];
    if (brief) lines.push(brief);
    lines.push("");

    if (bundle.chokepoints) {
      lines.push("## Network Resilience");
      lines.push(`Across ${bundle.chokepoints.graph_stats.paths_observed} observed paths, the top adversarial chokepoint is:`);
      const adv = bundle.chokepoints.adversarial_chokepoints[0];
      if (adv) {
        lines.push(`- **AS${adv.asn} (${adv.holder})** — centrality ${adv.centrality.toFixed(1)} (would re-route ${Math.round(adv.raw_score)} peer→target shortest paths if removed)`);
      }
      lines.push("");
    }

    if (bundle.scenarios?.taiwan_china) {
      const tw = bundle.scenarios.taiwan_china;
      lines.push("## US-Relevance Analog");
      lines.push(`Same methodology applied to ${tw.scenario_name}:`);
      lines.push(`- ${tw.totals.exposed_targets}/${tw.cities.length} Taiwanese target ASes exposed to PRC adjacency`);
      lines.push(`- Peak exposure: ${tw.totals.max_exposure}/100`);
      lines.push(`- ${tw.totals.total_prc_adjacencies} direct PRC-adjacencies across all targets`);
      lines.push("");
    }

    lines.push("---");
    lines.push("*Generated by Cyber Terrain Mapper. Sources: RIPE NCC RIS (rrc15/rrc16/rrc18), RIPE Stat API, UCDP GED v25.1.*");
    return lines.join("\n");
  };

  // Wargame-tool ready JSON — structured schema for downstream consumption
  const buildJSON = (): string => {
    const out = {
      schema_version: "cyber-terrain-mapper/1.0",
      generated_at:   new Date().toISOString(),
      target_city:    city.name,
      target_asn:     city.asn,
      target_coords:  { lat: city.lat, lon: city.lon },
      sample_date:    date,
      bgp_period:     periodMeta,
      threat_score:   t,
      bgp_signal:     periodData,
      kinetic_events: city.events.filter((e) => {
        const d = Math.abs(
          (new Date(e.event_date).getTime() - new Date(date).getTime()) /
            86400000,
        );
        return d <= 14;
      }),
      peer_timeline:  city.peer_timeline,
      chokepoints:    bundle.chokepoints,
      scenarios:      bundle.scenarios,
    };
    return JSON.stringify(out, null, 2);
  };

  const download = (filename: string, content: string, mime: string) => {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const stamp = date.replace(/-/g, "");

  return (
    <div className="export-row">
      <button
        className="export-btn"
        onClick={() =>
          download(
            `cyber-terrain-${city.name}-${stamp}.md`,
            buildMarkdown(),
            "text/markdown",
          )
        }
        title="Download analyst-readable Markdown brief"
      >
        ⬇ Brief (.md)
      </button>
      <button
        className="export-btn"
        onClick={() =>
          download(
            `cyber-terrain-${city.name}-${stamp}.json`,
            buildJSON(),
            "application/json",
          )
        }
        title="Download wargame-tool ready JSON"
      >
        ⬇ Wargame data (.json)
      </button>
    </div>
  );
}
